SRC += swapper.c
SRC += oneshot.c
SRC += maccel.c

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360

CAPS_WORD_ENABLE = yes
UNICODEMAP_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
MOUSEKEY_ENABLE = yes
COMBO_ENABLE = yes
